language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "0wr95BJZqf7DXOJ/W0y6a/bmnVd5UnHFB4tPJVyhBN0h3xgeFFswtrqkNQqdWg2FH8rULe4YKo1rvKAtS/WErLAo29wHdRgAJKzunGg/2tRwXfmRU1ze/oCSDGEqbLB/YO4m+kPud4QcckLz6ehbPEeM/FXnd0F87y86CijURZp65PVS/xBdGH7HOBWCPWTAnCYUTwnqNXdJ02mwF+tp7XOLOPQtCpY23DaQTptTB5n59Igcg/HAu5YFuMImG7JSegnbIAMzArmb/8+IcCPbd459sr8j7ZoJW9gu+ZVVMLv+fsQbm+kOnmJD4713f3e5SnpdSXMU18Oq146HMJczcsUGlPCZl1nCsRkWbdkVskZjr0M8KEhauq8FFYsUqUjrhnEnZy/Va99NjYae75tRUDB7iVt78C5qFth9uC83OhSWSaVSwuQWSu3be3xOrf9a2p5IuGebTtKR8IOgFFNs2iISXOKoibR3Ambdxug/tt07TnQQhHMfBsfrfG2mEkYzajWXgdK5xMou5MbcFQ8/Z+f+pGhBLCte8yg+9E97UFJxaEaIxuwPW/qhHZc2K6vKKgWliuFs1OtZyB+wnasSCSlUcNGSEuGQsgBt4u4efkCVicDW2jNcXHMyDTkULadPhFtJ4OC6n6DkeqCoRr82kkt3fYxlxq9ZJbxz65OwPmY="
  app:
    master: pokemon-api-moniwaterhouse
